version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "deps(dependabot)"
    groups:
      all-dependencies:
        patterns:
          - "*"
